# Generated by Django 4.0.6 on 2022-08-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Mailing', 'verbose_name_plural': 'Mailings'},
        ),
    ]
